name: nfc_antenna_info_flutter
description: Flutter plugin for retrieving precise NFC antenna information to accurately locate NFC chips on devices.
repository: https://github.com/BBarisKilic/Nfc-Antenna-Info-Flutter/tree/main/nfc_antenna_info_flutter
version: 1.0.0

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: nfc_antenna_info_flutter_android

dependencies:
  flutter:
    sdk: flutter
  # A package that provides annotations for expressing developer intentions that cannot be inferred
  # through static code analysis.
  meta: ^1.15.0
  nfc_antenna_info_flutter_android: ^1.0.0
  nfc_antenna_info_flutter_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^7.0.0
