name: nfc_antenna_info_flutter
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: 'none'


environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: nfc_antenna_info_flutter_android

dependencies:
  flutter:
    sdk: flutter
  # A package that provides annotations for expressing developer intentions that cannot be inferred
  # through static code analysis.
  meta: ^1.15.0
  nfc_antenna_info_flutter_android:
    path: ../nfc_antenna_info_flutter_android
  nfc_antenna_info_flutter_platform_interface:
    path: ../nfc_antenna_info_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
