name: nfc_antenna_info_flutter_android
description: Android implementation of the nfc_antenna_info_flutter plugin
repository: https://github.com/BBarisKilic/Nfc-Antenna-Info-Flutter/tree/main/nfc_antenna_info_flutter_android
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: nfc_antenna_info_flutter
    platforms:
      android:
        package: com.bbkdevelopment
        pluginClass: NfcAntennaInfoFlutterPlugin
        dartPluginClass: NfcAntennaInfoFlutterAndroid

dependencies:
  flutter:
    sdk: flutter
  # A package that provides annotations for expressing developer intentions that cannot be inferred
  # through static code analysis.
  meta: ^1.15.0
  nfc_antenna_info_flutter_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^7.0.0
