name: nfc_antenna_info_flutter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/nfc_antenna_info_flutter.yaml"
      - "nfc_antenna_info_flutter/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nfc_antenna_info_flutter.yaml"
      - "nfc_antenna_info_flutter/**"

jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.24.0
      working_directory: nfc_antenna_info_flutter

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: nfc_antenna_info_flutter


  android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nfc_antenna_info_flutter/example

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-34

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: |
            adb shell getprop sys.boot_completed
            adb wait-for-device shell echo "Device is ready."
            flutter pub get
            fluttium test flows/test_platform_name.yaml -d android --verbose || echo "Fluttium test failed with exit code $?"
          working-directory: nfc_antenna_info_flutter/example
